### ISSUE TITLE
IndexError: index 21761 is out of bounds for axis 0 with size 10809 during training

### ISSUE THREAD

**Issue by abhi0987** [isseu/emotion-recognition-neural-networks#28]
I have process the image using cvs_to_numpy, then when i try to train the following error appears:

Run id: expression_detection
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 32427
Validation samples: 9495
--
Exception in thread Thread-3:
Traceback (most recent call last):
  File "E:\AnacondaInstaller\envs\ML_learn\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "E:\AnacondaInstaller\envs\ML_learn\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AnacondaInstaller\envs\ML_learn\lib\site-packages\tflearn\data_flow.py", line 187, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "E:\AnacondaInstaller\envs\ML_learn\lib\site-packages\tflearn\data_flow.py", line 222, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "E:\AnacondaInstaller\envs\ML_learn\lib\site-packages\tflearn\utils.py", line 187, in slice_array
    return X[start]
IndexError: index 21761 is out of bounds for axis 0 with size 10809

Can someone guide me in this issue?

**Comment by choubaguaiyayiya** [comment]
I have the same problem. Have you solved it？
