### ISSUE TITLE
Cannot convert CSV to NPY

### ISSUE THREAD

**Issue by halfbyte-tech** [isseu/emotion-recognition-neural-networks#30]
I am unable to run cvs_to_numpy.py in python 3.6.3 as it throws an error:
`Traceback (most recent call last):`
`  File "cvs_to_numpy.py", line 7, in <module>`
`    cascade_classifier = cv2.CascadeClassifier(CASC_PATH)`
`NameError: name 'CASC_PATH' is not defined`

**Comment by halfbyte-tech** [comment]
SOLVED! 
Simply place `constants.py` in the data directory!

**Comment by NomiMalik0207** [comment]
OpenCV Error: Assertion failed (!empty()) in cv::CascadeClassifier::detectMultiScale, file C:\bld\opencv_1496444098483\work\opencv-3.2.0\modules\objdetect\src\cascadedetect.cpp, line 1681
Traceback (most recent call last):
  File "D:/Masters/Research/facial expression detection using neural nets/emotion-recognition-neural-networks-master/data/cvs_to_numpy.py", line 72, in <module>
    image = data_to_image(row['pixels'])
  File "D:/Masters/Research/facial expression detection using neural nets/emotion-recognition-neural-networks-master/data/cvs_to_numpy.py", line 60, in data_to_image
    data_image = format_image(data_image)
  File "D:/Masters/Research/facial expression detection using neural nets/emotion-recognition-neural-networks-master/data/cvs_to_numpy.py", line 23, in format_image
    minNeighbors = 5
cv2.error: C:\bld\opencv_1496444098483\work\opencv-3.2.0\modules\objdetect\src\cascadedetect.cpp:1681: error: (-215) !empty() in function cv::CascadeClassifier::detectMultiScale
 Got these errors.. Can someone help me??
