### ISSUE TITLE
Unable to slice using numpy indices in cvs_to_numpy.py

### ISSUE THREAD

**Issue by nimish1512** [isseu/emotion-recognition-neural-networks#9]
Traceback (most recent call last):
  File "cvs_to_numpy.py", line 71, in <module>
    image = data_to_image(row['pixels'])
  File "cvs_to_numpy.py", line 59, in data_to_image
    data_image = format_image(data_image)
  File "cvs_to_numpy.py", line 16, in format_image
    gray_border[((150 / 2) - (SIZE_FACE/2)):((150/2)+(SIZE_FACE/2)), ((150/2)-(SIZE_FACE/2)):((150/2)+(SIZE_FACE/2))] = image
TypeError: slice indices must be integers or None or have an __index__ `method

**Comment by nimish1512** [comment]
Turns out the index calculated was floating point. Typecasting it to Integer solved the problem
